# set font
font_family Maple Mono Italic

# Font size
font_size 12

# Font size adjustment
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# cursor
shell_integration no-cursor
cursor_shape beam

# Padding
window_padding_width 7
window_padding_height 10

# Scrollback
scrollback_lines 3000

# Hyprland will handle transparency
background_opacity 1

#COLORS!

cursor          #AC82E9

foreground      #d8cab8
background      #141216

selection_foreground   #141216
selection_background   #d8cab8

# ANSI colors
# black
color0               #2b2135
# brblack
color8               #92fcfa
# red
color1               #fc4649
# brred
color9               #fc4649
# brgreen
color10               #e08d9c
# green
color2              #ebbcc5
# yellow
color3               #AC82E9
# bryellow
color11              #AC82E9
# blue
color4               #4e2ab1
# brblue
color12              #4e2ab1
# magenta
color5               #f3fc7b
# brmagenta
color13              #f3fc7b
# white
color7               #8F56E1
# brcyan
color14              #8F56E1
# cyan
color6               #fc92fc
# brwhite
color15              #d8cab8