# set font
font_family Maple Mono Italic

# Font size
font_size 12

# Font size adjustment
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# cursor
shell_integration no-cursor
cursor_shape beam

# Padding
window_padding_width 7
window_padding_height 10

# Scrollback
scrollback_lines 3000

# Hyprland will handle transparency
background_opacity 1

#COLORS!

cursor          #AC82E9

foreground      #d8cab8
background      #141216

selection_foreground   #141216
selection_background   #d8cab8

color0               #2b2135
color8               #92fcfa
color1               #fc4649
color9               #fc4649
color10               #e08d9c
color2              #ebbcc5
color3               #AC82E9
color11              #AC82E9
color4               #4e2ab1
color12              #4e2ab1
color5               #f3fc7b
color13              #f3fc7b
color7               #8F56E1
color14              #8F56E1
color6               #fc92fc
color15              #d8cab8