# Execute your favorite apps at launch
$WALLDIR = ~/Pictures/wallpapers
# cross-desktop portal for hyprland
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd  XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# polkit authentication agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Background setter and wallpaper manager
exec = swww-daemon
exec = swww img $HOME/Pictures/wallpapers/celeste.png

# Status bar, notification daemon, bluetooth and network applets, clipboard manager, VPN
exec-once = waybar
# exec-once = waybar --config ~/.config/waybar/conf/v4-config-bottom.jsonc

# notification daemon
exec-once = mako

#bluetooth applet
exec-once = blueman-applet
# network manager applet
exec-once = nm-applet --indicator
# clipboard manager
exec-once = wl-paste --watch cliphist store

# VPN connection
exec-once = mullvad-vpn & mullvad connect
#exec = ~/.config/HyprV/hyprv_util setbg
